#include <iostream>
#include <string>
#include<conio.h>
using namespace std;
struct TuVung
{
    string tu_tieng_anh;
    string tu_tieng_viet;
};

void Translate(TuVung a[], int so_tu){
    for (int i = 0; i < so_tu; i++)
    {
        cout << a[i].tu_tieng_anh;
        getchar();
        cout << a[i].tu_tieng_viet << endl;
        getchar();
    }
    
}
int main (){
    TuVung toeic[205 - 25 + 1] = {
        {"Railing", "lan can"},
        {"Put on", "dang deo"},
        {"wear", "da deo san tren nguoi"},
        {"lean over", "tua vao"},
        {"hold", "cam"},
        {"cabinet", "tu dung do"},
        {"passengers", "hanh khach"},
        {"line up", "xep hang"},
        {"gather", "tu tap"},
        {"reaching", "voi toi"},
        {"carry", "mang vac"},
        {"spectators", "nguoi xem o ngoai troi"},
        {"cash", "tien mat"},
        {"cash register", "may tinh tien"},
        {"fill", "lap day *am ngan"},
        {"feel", "cam nhan *am dai"},
        {"arrange", "sap xep"},
        {"jewelry", "trang suc"},
        {"display rack", "gia trung bay"},
        {"try on", "thu"},
        {"bracelets", "vong tay"},
        {"hanger", "moc quan ao"},
        {"merchandise", "hang hoa"},
        {"grocery", "hang hoa"},
        {"fence", "hang rao"},
        {"stair", "cau thang"},
        {"leave", "roi di hoac bo lai *am dai"},
        {"live", "song *am ngan"},
        {"point at", "chi vao"},
        {"badge", "the ghi chuc danh"},
        {"counter", "quay tinh tien"},
        {"fold", "gap"},
        {"handbag", "tui deo tay"},
        {"take off", "coi >< put on"},
        {"brochure", "to quang cao xin"},
        {"leaflets", "to roi"},
        {"assemble", "lap rap"},
        {"construction", "xay dung"},
        {"climb", "leo treo *b cam"},
        {"alongside", "doc theo"},
        {"hang", "treo"},
        {"comlb", "chai (dau)"},
        {"distribute", "phan phat"},
        {"handouts", "tai lieu truyen tay"},
        {"greeting", "loi chao"},
        {"pull", "keo"},
        {"push", "day"},
        {"suitcase", "hanh ly"},
        {"luggage", "hanh ly"},
        {"stand in line", "xep hang"},
        {"loading into", "tai vao"},
        {"memos", "thong bao(ban ghi nho)"},
        {"attach", "dinh (gan)"},
        {"bullet in board", "bang thong bao"},
        {"monitor", "man hinh may tinh"},
        {"corner", "goc"},
        {"grassy", "nhieu co"},
        {"path", "duong nho"},
        {"fountain", "dai phun nuoc"},
        {"bench", "ghe dai"},
        {"rake", "cai cao"},
        {"leaf", "la"},
        {"leaves", "la so nhieu"},
        {"pave", "lat duong be tong"},
        {"pavement", "via he"},
        {"hand rail", "lan can co tay vin"},
        {"shade", "bong (do bong)"},
        {"branch", "canh cay (chi nhanh)"},
        {"fixture", "co dinh"},
        {"perdestrians", "nguoi di bo"},
        {"intersection", "nga tu"},
        {"scaffold", "gian giao"},
        {"erect", "dung len"},
        {"archway", "cong vom"},
        {"ceiling", "tran nha"},
        {"pots", "chau"},
        {"Organize", "sap xep"},
        {"measure", "do dac"},
        {"exchange", "trao doi"},
        {"installation", "su sap dat"},
        {"dig", "dao"},
        {"spead out", "trai ra"},
        {"bulletin board", "bang tin"},
        {"refreshment", "do an nhe"},
        {"illuminate", "chieu sang"},
        {"bush", "bui cay"},
        {"board", "len tau xe"},
        {"brower", "ngam nghia"},
        {"unoccupied", "khong co nguoi"},
        {"carpeting ", "tam tham"},
        {"various ", "nhieu"},
        {"lifting ", "nang (ta)"},
        {"pack","dong goi"},
        {"presentation","bai thuyet trinh"},
        {"trim","tia (cay)"},
        {"lawn","bai co"},
        {"overlooking","nhin ra"},
        {"beneath","duoi"},
        {"pour","rot"},
        {"apron","tap de"},
        {"garment","hang may mac"},
        {"toward","huong"},
        {"curtains","rem cua"},
        {"purchase","mua"},
        {"metal","kim loai"},
        {"direct","truc tiep"},
        {"budget","ngan sach"},/**/
        {"assignment","nhiem vu"},
        {"negotiation","dam phan"},
        {"postpone","hoan"},
        {"proposal","de xuat"},
        {"merger","sat nhap"},
        {"plug","cam o dien"},
        {"maintenance","bao tri"},
        {"workplace","noi lam viec"},
        {"household","ho gia dinh"},
        {"descend","di xuong"},
        {"adjusting","dieu chinh"},
        {"approved","tan thanh, phe duyet"},
        {"appreciate","danh gia cao"},
        {"give out","phan phat"},
        {"results","ket qua"},
        {"Probably","co le"},
        {"shuttle bus","xe buyt dua don"},
        {"due","qua han"},
        {"fairly low","kha thap"},
        {"preference","so thich"},
        {"upgrade","nang cap"},
        {"propose","de xuat"},
        {"analysis","bang phan tich"},
        {"blind","mu"},
        {"balcony","ban cong"},
        {"appointment","cuoc hen"},
        {"invitaion","giay moi"},
        {"promotion","su thang chuc"},
        {"vice","pho (chu tich)"},
        {"reception","su tiep nhan"},
        {"manual","sach huong dan"},
        {"article","bai viet"},
        {"plant","nha may"},
        {"policy","chinh sach"},
        {"envelope","phong bi"},
        {"tenant","nguoi thue nha"},
        {"announce","cong bo"},
        {"unload","do hang"},
        {"operate","van hanh"},
        {"package","buu kien"},
        {"promotion","thang tien"},
        {"stand","gian hang"},
        {"supply","nguon"},
        {"convention","hoi nghi"},
        {"supplier","nha cung cap"},
        {"basement","ham"},
        {"vase","lo hoa"},
        {"gesture","chi tay"},
        {"a patient","1 benh nhan"},
        {"awning","mai hien"},
        {"authorize","cap quyen"},
        {"purchase","mua"},
        {"Probably ","co le"},
        {"commercial","quang cao"},
        {"lent","vay"},
        {"rent","thue"},
        {"lease  ","cho thue"},
        {"vendor ","nguoi ban"},
        {"lobby ","sanh"},
        {"renovaion ","cai tao"},
        {"stapling","dap ghim"},
        {"sawing","cua (go)"},
        {"wiping  ","lau chui"},
        {"sweep", "quet"},
        {"provide ","cung cap"},
        {"product","san pham"},
        {"appreciate  ","danh gia"},
        {"extra ","ban sao"},
        {"responsible  ","chiu trach nhiem"},
        {"delivery ","van chuyen"},
        {"striped  ","ke soc"},
        {" in mind. ","trong tam tri"},
        {"tight ","chat"},
        {"lobby ","sanh"}
    };
    Translate(toeic, so_tu);
    return 0;

}